name: slack workflow test

on: push

jobs:
  my-job:
    name: slack job
    runs-on: ubuntu-latest
    steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        payload: |
          {
            "blocks": [
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "\n:alert::alert::alert::alert:\n\n*GitHub Action Failure:*\n\n Main scheduler workflow has failed!"
                },
                "accessory": {
                  "type": "image",
                  "image_url": "https://ca.slack-edge.com/T03TJ3P61-U034J2897V0-1d3e4b813a11-72",
                  "alt_text": "failed workflow"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Run",
                      "emoji": true
                    },
                    "value": "Run",
                    "url": "${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
